@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":"Junior",
	"email":"junior5151@email.com",
	"password":"12345"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email":"junior5151@email.com",
	"password":"12345"
}

